#!/usr/bin/env python3

import argparse
import subprocess
import sys

import nibabel
import numpy
import pandas

def main():
    parser = argparse.ArgumentParser(
        description="Transport atlas labels to subject space "
            "and create a volumetry report")
    parser.add_argument("subject", help="Subject image")
    parser.add_argument(
        "reference", help="Template image of atlas or transform")
    parser.add_argument("labels", help="Label image of atlas")
    parser.add_argument("dictionary", help="Names of the labels")
    parser.add_argument("prefix", help="Prefix of output files")
    parser.add_argument("volumes", help="Path to the volumes file")
    arguments = parser.parse_args()
    
    # Transform files suffixes, in the order they should be fed to 
    # antsApplyTransforms
    suffixes = ["1Warp.nii.gz", "0GenericAffine.mat"]
    
    is_transform = any(arguments.reference.endswith(x) for x in suffixes)
    
    if is_transform:
        if arguments.reference.endswith("0GenericAffine.mat"):
            stem = arguments.reference[:-len("0GenericAffine.mat")]
        else:
            stem = arguments.reference[:-len("1Warp.nii.gz")]
        transforms = ["{}{}".format(stem, x) for x in suffixes]
    else:
        subprocess.check_call([
            "antsRegistrationSyN.sh", "-d", "3", "-p", "f",
            "-n", subprocess.check_output("nproc").strip(),
            "-f", arguments.subject, "-m", arguments.reference, 
            "-t", "s", "-o", arguments.prefix])
        transforms = ["{}{}".format(arguments.prefix) x for x in suffixes]
    
    subprocess.check_call([
        "antsApplyTransforms", "-d", "3",
        "-i", arguments.labels, "-r", arguments.subject,
        "-n", "NearestNeighbor",
        "-o", arguments.prefix+"_labels.nii.gz"]
        + ["-t", transforms[0], "-t", transforms[1]])
    
    dictionary = pandas.read_csv(
        arguments.dictionary, names=["label", "name", "r", "g", "b", "a"], sep=" ")
    
    image = nibabel.load(arguments.prefix+"_labels.nii.gz")
    voxel_volume = numpy.abs(numpy.linalg.det(image.affine[:3,:3]))
    data = image.get_data().astype(int)
    volumes = []
    for row in dictionary.iterrows():
        count = (data == row[1].label).sum()
        volumes.append([row[1]["name"], row[1]["label"], voxel_volume*count])
    volumes = pandas.DataFrame(volumes, columns=["Name", "Label", "Volume (mm³)"])
    volumes.to_excel(arguments.volumes, index=False)
    
if __name__ == "__main__":
    sys.exit(main())
