#!/usr/bin/env python3

import argparse
import sys

import nibabel
import numpy

import transform_image

def main():
    parser = argparse.ArgumentParser(
        description="Reorient data where the sample was placed "
        "feet-first-supine, but head-first-supine was specified on the scanner")
    parser.add_argument("source")
    parser.add_argument("destination")
    arguments = parser.parse_args()

    source = nibabel.load(arguments.source)

    # Mismatch between HFS and FFS means flipping the LR and rostro-caudal 
    # (mapped to IS) axes around the image center. In RAS space, this is:
    transform = numpy.diag([-1., 1., -1.])
    
    destination = nibabel.Nifti1Image(
        source.dataobj, transform_image.transform_matrix(source, transform))
    nibabel.save(destination, arguments.destination)

if __name__ == "__main__":
    sys.exit(main())
