#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys

def main():
    parser = argparse.ArgumentParser(description="Determine best BET threshold on image")
    parser.add_argument("input", help="Input image")
    parser.add_argument(
        "-f", action="append", default=[], help="BET threshold value")
    arguments = parser.parse_args()
    
    print("Running N4BiasFieldCorrection...")
    subprocess.check_call([
        "N4BiasFieldCorrection", "-i", arguments.input, "-o", "N4.nii.gz"])
    
    for value in arguments.f:
        print(f"Running BET with threshold {value}...")
        subprocess.check_call([
            "bet", "N4.nii.gz", f"bet_{value}", 
            "-f", value, "-R", "-g", "0", "-m"])
    processes = []
    for value in arguments.f:
        process = subprocess.Popen([
            "itksnap", "-g", "N4.nii.gz", "-s", f"bet_{value}_mask.nii.gz"])
        processes.append(process)
    
    for process in processes:
        process.communicate()
    
    for value in arguments.f:
        os.remove(f"bet_{value}.nii.gz")
        os.remove(f"bet_{value}_mask.nii.gz")

if __name__ == "__main__":
    sys.exit(main())
