#!/usr/bin/env python3

import argparse
import sys

import nibabel
import numpy

import transform_image

def main():
    parser = argparse.ArgumentParser(
        description="Create a left-right mirror of the source image")
    parser.add_argument("source")
    parser.add_argument("destination")
    arguments = parser.parse_args()

    source = nibabel.load(arguments.source)

    # Flip LR axis
    transform = numpy.diag([-1., 1., 1.])

    destination = nibabel.Nifti1Image(
        source.dataobj, transform_image.transform_matrix(source, transform))
    nibabel.save(destination, arguments.destination)

if __name__ == "__main__":
    sys.exit(main())
